export const strings = {
  documentTitle: "Good First Issue Finder",
  noFavoriteIssues: "No favorite issues yet. Save some to see them here!",
  favoriteIssues: "Favorite Issues",
  updatedOn:"Updated on",
  NoAssignee:"No Assignee",
  languageSelection: "Select a language",
  allLanguages: "All languages",
  logoText: "FGFI",
  paginationPrev: "Previous",
  paginationNext: "Next",
  noIssuesFound: "No issues found.",
  filterIssuesPlaceholder: "Filter issues",
  error: "Error",
  accessDeniedError: "Access denied. Please check your permissions.",
  noResponseError: "No response from server. Please try again later.",
  unexpectedError: "An unexpected error occurred. Please try again.",
  noAssignee: "No assignee yet",
  listItemError: "Error loading data",
  listItemReloadButtonLabel: "Reload",
  searchLanguages: "Search languages"
};
